-- up migration
ALTER TABLE users
  ALTER COLUMN created_at TYPE TIMESTAMP,
  ALTER COLUMN updated_at TYPE TIMESTAMP;

ALTER TABLE posts
  ALTER COLUMN created_at TYPE TIMESTAMP,
  ALTER COLUMN deleted_at TYPE TIMESTAMP,
  ALTER COLUMN updated_at TYPE TIMESTAMP;

ALTER TABLE comments
  ALTER COLUMN created_at TYPE TIMESTAMP,
  ALTER COLUMN deleted_at TYPE TIMESTAMP,
  ALTER COLUMN updated_at TYPE TIMESTAMP;
